version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      postgres:
      container_name: postgres
      image: postgres
      ports:
      - '5432:5432'
      environment:
      POSTGRES_USER: organizer
      POSTGRES_PASSWORD: organizer
      POSTGRES_DB: organizer
  organization-service:
    container_name: organization-service
    build: ./organization-service
    ports:
    - '8081:8081'
  environment:
    - PORT=8081
    - POSTGRES_URL=postgres://organizer:organizer@postgres:5432/organizer
    - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    - KAFKA_TOPIC=topic1
  depends_on:
   - postgres
   - kafka


   
     
      
     

